# The main config file for your Jekyll template

# Site settings
title: Hopped Up Gaming East               # used for the html title of every page
desc: >
  Hopped Up Gaming East is your favorite East Coast Podcast that covers Craft Beer,
  Video Games, Pop culture and everything nerdy. Join Evan, Matthew, Ben and Tim every
  week for the two craft beer reviews, the latest in what everyone is playing and/or
  watching.

url: http://hoppedupeast.com      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: info@hoppedupeast.com
author: HUGE Crew
twitter_username: hoppedupeast
github_username: 
github_source: 

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Podcast
    url: /podcast/
    desc: Where to listen to the Hopped Up Gaming East Podcast
  - title: Projects
    url: /projects/
    desc: Projects the Hopped Up Gaming East Crew has worked on
  - title: Six Pack
    url: /6pack/
    desc: The 6 most highly rated beers from the Hopped Up Gaming East crew
  - title: About
    url: /about/
    desc: Learn more about Hopped Up Gaming East

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

# HUGE COLORS
# Brown: #3b2314
# Orange: #faaf40
# Cream: #ffdea5

