# Site
name: "Hopped-Up Gaming: East"
title: "Hopped-Up Gaming: East"
description: "Eastern Canadian Craft Beer and Video Games Podcast"
meta_description: "Eastern Canadian Craft Beer and Video Games Podcast"
logo: 'assets/images/huge-logo-sm.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: ''
email: 'hoppedupeast@gmail.com'
google_analytics: 'UA-111791664-2'
disqus: ''

#Podcast Providers:
hipcast: 'https://www.hipcast.com/podcast/HJfyJb'
spotify: 'https://open.spotify.com/show/2dTRwdB4bHYsCI2CN9OV2m'
googlepod: 'https://play.google.com/music/m/I2ovy32ius4usiwhnuitgnh5ltu?t=Hopped-Up_Gaming_East'
applepod: 'https://podcasts.apple.com/us/podcast/hopped-up-gaming-east/id797058638'

#XCOMMITTEE
xcom-hipcast: 'https://www.hipcast.com/podcast/HWK5rrWs'
xcom-spotify: 'https://open.spotify.com/show/1z0C7QHykxMdrCQNxqqKCw'
xcom-applepod: 'https://podcasts.apple.com/gb/podcast/x-committee/id979571952'

#Social
facebook: 'https://www.facebook.com/hugeast/'
instagram: 'https://www.instagram.com/hoppedupeast'
twitter: 'https://www.twitter.com/hoppedupeast'
untappd: 'https://untappd.com/user/HoppedUpEast'
discord: 'https://bit.ly/hoppedupdiscord'

# sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  sal:
    name: Evan
    display_name: Evan
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: oakeef@gmail.com
    # web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/stuffwithevan
    description: "Member of Hopped-Up Gaming: East since 2014. Loves 80's cars, music and movies. Big fan of Dark Souls."
  # john:
  #   name: John
  #   display_name: John
  #   gravatar: b1cc14991db7a456fcd761680bbc8f81
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net/category/jekyll-themes/
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge